x-airflow-common: &airflow-common
  build:
    context: ./airflow
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__WEBSERVER__SECRET_KEY: "airflow-student-secret"
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    MLFLOW_TRACKING_URI: http://mlflow:5000
    MODEL_NAME: churn_prediction_model
    PYTHONPATH: /opt/project
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ../../../:/opt/project
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    container_name: student_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.17.2
    container_name: student_mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --serve-artifacts
      --artifacts-destination /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      postgres:
        condition: service_healthy

  airflow-init:
    <<: *airflow-common
    container_name: student_airflow_init
    command: >
      bash -c "airflow db migrate &&
      airflow users create --username airflow --password airflow --firstname Student --lastname Project --role Admin --email airflow@example.com"

  airflow-webserver:
    <<: *airflow-common
    container_name: student_airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: student_airflow_scheduler
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  fastapi:
    build:
      context: ../../../serving_pipeline/simple_api
    container_name: student_fastapi
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_NAME: churn_prediction_model
      MODEL_ALIAS: production
      INFERENCE_LOG_PATH: /app/logs/inference_log.jsonl
    ports:
      - "8000:8000"
    volumes:
      - fastapi_logs:/app/logs
    depends_on:
      - mlflow

volumes:
  postgres_data:
  mlflow_data:
  fastapi_logs:
